server:
  port: 9015
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_db
    username: root
    password: Retromar12345_
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.learning.utils.CustomNamingStrategy
com:
  learning:
    jwtSecret: bankapp
    jwtExpirationMs: 86400000

   # jwtSecret: bankapp

